# Generated by Django 3.2.2 on 2021-05-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210501_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
